### Pandas
Basic Datastructure:
1. Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). 
2. DataFrame is a 2-dimensional labeled data structure with columns of potentially different types
3. Panel is a somewhat less-used, but still important container for 3-dimensional data. The term panel data is derived from econometrics and is partially responsible for the name pandas: pan(el)-da(ta)-s. 

#### Examples:
DataFrame:(Quick tutorial:https://www.tutorialspoint.com/python_pandas/python_pandas_dataframe.htm)
1. create dataframe
2. select and index
3. convert

In [2]:
import pandas as pd
import numpy as np
#df=pd.read_csv('clean_dataset.csv', sep=',',header='infer')
df = pd.DataFrame(np.random.randn(8, 4), columns = ['A', 'B', 'C', 'D'])
#print df['A']< 0
#print "subset:"
#print df[df['A']< 0]
df.loc[:,'A']
tmp_data = df[df['A'] < 0]
print type(tmp_data.values)
#print tmp_data
print df
print df[['A','B']]

<type 'numpy.ndarray'>
          A         B         C         D
0  1.217857 -0.524437 -0.124648 -0.609837
1  0.048445 -0.798330  0.599997  0.146787
2  2.286321  0.300198  2.423772  0.170754
3  2.358383  0.176296  0.408424 -0.650785
4  1.130357 -0.185300 -0.088679 -0.407462
5  1.768876  0.199540 -0.297201 -0.105841
6 -0.970151 -1.104882  0.115520  0.059623
7 -0.664342 -0.149694  0.370762 -0.165210
          A         B
0  1.217857 -0.524437
1  0.048445 -0.798330
2  2.286321  0.300198
3  2.358383  0.176296
4  1.130357 -0.185300
5  1.768876  0.199540
6 -0.970151 -1.104882
7 -0.664342 -0.149694


## Feature Engineering:
ref: 
https://www.youtube.com/watch?v=LMlzHfJPvjI&list=PL7tqo8Xk0expKfOuKz9AWWQ0rqIhtjjfP&index=16

From raw data to useful features
1. Feature extraction, preprocessing
2. Feature selection
    1. Remove useless features
    2. sklearn: statistics, correlation, model_based
    2. Feature Generation

E.g. Automatic Feature Generation:
1. multiplicative interactions
2. Function transformation: $x^2, sqrt(x), ln(x)$
3. Automated Threshold Selection:
    1. Turn a numerical variable into a binary
    2. Find a cut off point automatically
    
Automatic Feature Selection：
1. Correlation Filtering:
    How to choose among those correlated features? 


## Feature preprocessing
1. scaling
     1. to [0,1]:
        sklearn.preprocessing.MinMaxScaler
     2. to mean=0,std=1:
         sklearn.preprocessing.StandardScaler
     3. http://scikit-learn.org/stable/auto_examples/preprocessing/plot_all_scaling.html#sphx-glr-auto-examples-preprocessing-plot-all-scaling-py
2. outlier
4. encoding
     1. rank: set spaces between sorted values equal

### Feature encoding
reference: https://zh.coursera.org/learn/competitive-data-science/lecture/wckTQ/datetime-and-coordinates
#### Type of features
1. Numerical features
2. Categorical features
3. Ordinal features
4. Datetime and coordiantes
5. Handling missing values




In [31]:
##Sample code for one hot encoding
print "original: \n", test_ft
print '\n'
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
test_ft = [[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]]
enc.fit(test_ft)
print enc.n_values_
print enc.feature_indices_
print enc.transform(test_ft).toarray()
print '\n'
## select the transform fts
mask_ft = [False, True, False]
enc = OneHotEncoder(categorical_features=[1])
test_ft = [[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]]
enc.fit(test_ft)
print enc.n_values_
print enc.feature_indices_
print enc.transform(test_ft).toarray()

print 'original'


original: 
[[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]]


[2 3 4]
[0 2 5 9]
[[ 1.  0.  1.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  1.  0.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  1.  0.  1.  0.  0.]
 [ 0.  1.  1.  0.  0.  0.  0.  1.  0.]]


[3]
[0 3]
[[ 1.  0.  0.  0.  3.]
 [ 0.  1.  0.  1.  0.]
 [ 0.  0.  1.  0.  1.]
 [ 1.  0.  0.  1.  2.]]
original


In [7]:
enc = OneHotEncoder()
test_ft = [[1,2], [3,2]]
enc.fit(test_ft)
print enc.n_values_

[4 3]


In [11]:
mask_ft = map(bool,[0, 1 ,0])
print mask_ft

[False, True, False]


### Introduction for features importance in the Random Forest
ref: https://zh.coursera.org/learn/python-machine-learning/lecture/lF9QN/random-forests
<img src=rf.png>

In [ ]:
# visualize the random forest


In [ ]:
d